name: Android APK Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '4.2.1'

jobs:
  build-android:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
          SKIP_JDK_VERSION_CHECK: true

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Android Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Build Android Release AAB
        working-directory: android
        run: ./gradlew bundleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: educafric-debug-v${{ github.event.inputs.version || '4.2.1' }}.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: educafric-release-v${{ github.event.inputs.version || '4.2.1' }}.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Create release assets
        run: |
          mkdir -p release-assets
          cp android/app/build/outputs/apk/debug/app-debug.apk release-assets/educafric-v${{ github.event.inputs.version || '4.2.1' }}-debug.apk
          cp android/app/build/outputs/bundle/release/app-release.aab release-assets/educafric-v${{ github.event.inputs.version || '4.2.1' }}-release.aab
          
          echo "=== EDUCAFRIC v${{ github.event.inputs.version || '4.2.1' }} BUILD COMPLETE ===" > release-assets/BUILD_INFO.txt
          echo "Build Date: $(date)" >> release-assets/BUILD_INFO.txt
          echo "Commit: ${{ github.sha }}" >> release-assets/BUILD_INFO.txt
          echo "" >> release-assets/BUILD_INFO.txt
          echo "Files included:" >> release-assets/BUILD_INFO.txt
          echo "- educafric-v${{ github.event.inputs.version || '4.2.1' }}-debug.apk (Debug APK for testing)" >> release-assets/BUILD_INFO.txt
          echo "- educafric-v${{ github.event.inputs.version || '4.2.1' }}-release.aab (Release AAB for Google Play)" >> release-assets/BUILD_INFO.txt

      - name: Upload all release assets
        uses: actions/upload-artifact@v4
        with:
          name: educafric-android-release-v${{ github.event.inputs.version || '4.2.1' }}
          path: release-assets/