name: Simple Android Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '4.2.3-branded'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/public/
          echo "Checking for index.html..."
          test -f dist/public/index.html && echo "✓ index.html found" || echo "✗ index.html missing"

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platform-tools platforms;android-33 build-tools;33.0.0'
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
          SKIP_JDK_VERSION_CHECK: true

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: educafric-v${{ github.event.inputs.version }}-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Build Info
        run: |
          echo "EDUCAFRIC Android APK Build Complete"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Build Date: $(date)"
          echo "APK Location: android/app/build/outputs/apk/debug/app-debug.apk"
          ls -la android/app/build/outputs/apk/debug/ || echo "Debug APK not found"