name: Simple Android Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '4.2.3-branded'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          ls -la dist/public/
          echo "Checking for index.html..."
          test -f dist/public/index.html && echo "✓ index.html found" || echo "✗ index.html missing"

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Android SDK (JDK21 Compatible)
        run: |
          # Manual Android SDK setup for Java 21 compatibility
          sudo mkdir -p /opt/android-sdk
          sudo chown -R $USER:$USER /opt/android-sdk
          
          export ANDROID_HOME=/opt/android-sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
          echo "/opt/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/opt/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "/opt/android-sdk/build-tools/33.0.0" >> $GITHUB_PATH
          
          # Download and setup command line tools
          cd /tmp
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          
          # Accept licenses and install required packages
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-33"
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;33.0.0"
          
          echo "✅ Android SDK setup completed with JDK 21"

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: android
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export ANDROID_SDK_ROOT=/opt/android-sdk
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: educafric-v${{ github.event.inputs.version }}-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Build Info
        run: |
          echo "EDUCAFRIC Android APK Build Complete"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Build Date: $(date)"
          echo "APK Location: android/app/build/outputs/apk/debug/app-debug.apk"
          ls -la android/app/build/outputs/apk/debug/ || echo "Debug APK not found"